{-
 - Project Euler 45
 -
 - Triangle, pentagonal, and hexagonal numbers are generated by the following
 - formulae:
 -
 - Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
 - Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
 - Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
 -
 - It can be verified that T285 = P165 = H143 = 40755.
 -
 - Find the next triangle number that is also pentagonal and hexagonal.
 -}
module Euler45 (euler45) where

triNums = map tri [1..]
	where tri n = n*(n+1) `div` 2

isHex n = ceiling t == floor t
	where t = (sqrt(8*fromIntegral n +1) + 1)/4

isPent n = floor t == ceiling t
	where t = (sqrt(24*fromIntegral n + 1) +1) / 6 

--start after the 285th triangle number because that is in the example
euler45 = head . filter isPent . filter isHex . drop 285 $ triNums 
answer = euler45
